INSERT INTO tipo_enfermedad (nombre) VALUES ('Infecciosas y parasitarias');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Neoplasmas');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Sangre y sistema inmunológico');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Endócrinas');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Desórdenes mentales');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Sistema nervioso central y órganos sensoriales');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Enfermedades de los sentidos');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Sistema cardiocirculatorio');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Sistema respiratorio');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Sistema digestivo');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Enfermedades de la piel');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Aparato locomotor');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Sistema genitourinario');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Embarazo, parto y puerperio');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Feto y del recién nacido');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Congénitas, malformaciones y alteraciones cromosómicas');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Síntomas y observaciones clínicas o de laboratorio');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Lesiones, heridas, intoxicaciones y otros factores externos');
INSERT INTO tipo_enfermedad (nombre) VALUES ('Caídas, golpes, y accidentes diversos');
